export const homeObjTwo = {
    id: 'portfolio',
    lightBg: true,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../Images/svg-2.svg').default,
    alt: 'phone',
    dark: false,
    primary: true,
    darkText: false,
}
