export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    textbox1: "Born and raised in North London, I am in my second year at Imperial College London, pursuing an MEng in Design Engineering. My primary interests lie in the field of human-centred and UX design. In these areas, I can use the wide-ranging skillset (engineering, computing, aesthetic design etc.) that I am accumulating, to create products or services that works to solve a problem being faced by a certain user.",
    textbox2: 'Design and engineering can create timeless solutions to many problems being faced by the modern world, from poverty to climate change to mental health issues. I work in close collaboration with my users to ensure that my solution does address problems at their core. I have carried out projects for a wide cross-section of users: from games for young children (3-4) in order to make learning maths a fun and interactive experience, to mobility devices for elderly people to reduce their risk of falling when they are outside. By keeping in constant contact with users, as well as stakeholders throughout the design process, I am able to accurately identify points in their life which could serve as design opportunities.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../Images/1.svg').default,
    alt: 'car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'portfolio',
    lightBg: true,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../Images/svg-2.svg').default,
    alt: 'phone',
    dark: false,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'gallery',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Join our Team',
    headline: 'Creating an account is extremely easy',
    description: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to go",
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../Images/svg-3.svg').default,
    alt: 'car',
    dark: false,
    primary: true,
    darkText: false,
}